<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productsRecords = [
            [
                'id'=> 1,
                'category_id' => 4,
                'brand_id' => '',
                'product_name' => 'Shirt',
                'product_code' => 'S001',
                'family_color' => 'Blue',
                'product_weight' => '5g',
                'group_code' => 'BS001',
                'product_price' => '250',
                'product_discount' => '50',
                'discount_type' => 'Christmas',
                'final_price' => '200',
                'product_video' => '',
                'description' => 'Shirts for all kind of stuff',
                'keywords' => 'shirts',
                'fabric' => 'Steal',
                'sleeve' => 'Longer',
                'fit' => 'Fat',
                'occasion' => 'Battle',
                'pattern' => '',
                'meta_title' => 'Steal shirts',
                'meta_description' => 'Needed for battle',
                'meta_keywords' => 'rust free',
                'is_featured' => 'YES',
                'wash_care' => '',
                'status' => 1,
            ],
            [
                'id'=> 2,
                'category_id' => 5,
                'brand_id' => '',
                'product_name' => 'Bra',
                'product_code' => 'B001',
                'family_color' => 'Green',
                'product_weight' => '5g',
                'group_code' => 'GB001',
                'product_price' => '450',
                'product_discount' => '20',
                'discount_type' => 'Christmas',
                'final_price' => '200',
                'product_video' => '',
                'description' => 'Bras for all kind of stuff',
                'keywords' => 'bra',
                'fabric' => 'cotton',
                'sleeve' => 'none',
                'fit' => 'slim',
                'occasion' => 'Battle',
                'pattern' => '',
                'meta_title' => 'Cotton bras',
                'meta_description' => 'Needed for battle',
                'meta_keywords' => 'rust free',
                'is_featured' => 'YES',
                'wash_care' => '',
                'status' => 1,
            ],
            [
                'id'=> 3,
                'category_id' => 5,
                'brand_id' => '',
                'product_name' => 'Panties',
                'product_code' => 'P001',
                'family_color' => 'Red',
                'product_weight' => '5g',
                'group_code' => 'RP001',
                'product_price' => '150',
                'product_discount' => '20',
                'discount_type' => 'Christmas',
                'final_price' => '100',
                'product_video' => '',
                'description' => 'Panties for sluts and hoes',
                'keywords' => 'panties',
                'fabric' => 'linnen',
                'sleeve' => 'none',
                'fit' => 'petit',
                'occasion' => 'Battle',
                'pattern' => '',
                'meta_title' => 'Panties for hookers',
                'meta_description' => 'Needed for battle',
                'meta_keywords' => 'rust free',
                'is_featured' => 'YES',
                'wash_care' => '',
                'status' => 1,
            ],
            [
                'id'=> 4,
                'category_id' => 6,
                'brand_id' => '',
                'product_name' => 'Socks',
                'product_code' => 'SO001',
                'family_color' => 'Black',
                'product_weight' => '5g',
                'group_code' => 'BSO001',
                'product_price' => '50',
                'product_discount' => '10',
                'discount_type' => 'Christmas',
                'final_price' => '10',
                'product_video' => '',
                'description' => 'Socks for all kind of stuff',
                'keywords' => 'socks',
                'fabric' => 'woll',
                'sleeve' => 'none',
                'fit' => 'Fat',
                'occasion' => 'Battle',
                'pattern' => '',
                'meta_title' => 'Cotton socks',
                'meta_description' => 'Needed for battle',
                'meta_keywords' => 'rust free',
                'is_featured' => 'YES',
                'wash_care' => '',
                'status' => 1,
            ],
            [
                'id'=> 5,
                'category_id' => 6,
                'brand_id' => '',
                'product_name' => 'Hats',
                'product_code' => 'H001',
                'family_color' => 'Orange',
                'product_weight' => '5g',
                'group_code' => 'OH001',
                'product_price' => '350',
                'product_discount' => '50',
                'discount_type' => 'Christmas',
                'final_price' => '200',
                'product_video' => '',
                'description' => 'Hats for all kind of stuff',
                'keywords' => 'hats',
                'fabric' => 'kashmir',
                'sleeve' => 'none',
                'fit' => 'Normal',
                'occasion' => 'Battle',
                'pattern' => '',
                'meta_title' => 'kashmir hats',
                'meta_description' => 'Needed for battle',
                'meta_keywords' => 'rust free',
                'is_featured' => 'YES',
                'wash_care' => '',
                'status' => 1,
            ],
        ];

        Product::insert($productsRecords);
    }
}
